[package]
name = "chemfuck-compiler"
version = "0.3.0"
authors = ["Colin Redman <20376935+credman0@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
regex="1"
lazy_static="1"